steps:
  - name: gcr.io/cloud-builders/gcloud
    id: 'Getting variables'
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=cloudbuild-env
      - --key=tristan-env

  - name: 'gcr.io/cloud-builders/npm'
    id: 'Installing dependencies'
    entrypoint: npm
    args: ['install']

  - name: node:10.15.1
    id: 'Also adding firebase tools'
    entrypoint: yarn
    args: ['add', 'firebase-tools']

  - name: 'node:10.15.1'
    id: 'Creating a production app'
    entrypoint: yarn
    args: ['build']

  - name: 'node:10.15.1'
    id: 'Deploying the app to production'
    entrypoint: './node_modules/.bin/firebase'
    args: ['deploy']
