steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=cloudbuild-env
      - --key=tristan-env
  # Insert other build steps here
  - name: 'building out the app'
    args: ['run', 'build']
  # Deploy
  - name: 'Deploying to firebase'
    args: ['run', 'deploy']
