steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - kms
      - decrypt
      - --ciphertext-file=.env.enc
      - --plaintext-file=.env
      - --location=global
      - --keyring=cloudbuild-env
      - --key=tristan-env

  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['install']

  - name: node:10.15.1
    entrypoint: yarn
    args: ['add', 'firebase-tools']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  - name: 'node:10.15.1'
    entrypoint: './node_modules/.bin/firebase'
    args: ['run', 'deploy']
