steps:
# Install
- name: 'gcr.io/$PROJECT_ID/packer'
  args: 
  - install
  - project_id=$PROJECT_ID
  - packer.json
# Test
- name: 'gcr.io/$PROJECT_ID/packer'
  args: ['run', 'test:unit']
# Build
- name: 'gcr.io/$PROJECT_ID/packer'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/$PROJECT_ID/packer'
  args: ['deploy']
  
